version: '3.8'

services:
  auth-service:
    build:
      context: ./services/auth-service
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - auth-data:/var/lib/postgresql/data
    depends_on:
      - auth-db

  auth-db:
    image: postgres:14
    environment:
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: auth_pass
      POSTGRES_DB: auth_db
    volumes:
      - auth-data:/var/lib/postgresql/data

  user-service:
    build:
      context: ./services/user-service
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    volumes:
      - user-data:/var/lib/postgresql/data
    depends_on:
      - user-db

  user-db:
    image: postgres:14
    environment:
      POSTGRES_USER: user_user
      POSTGRES_PASSWORD: user_pass
      POSTGRES_DB: user_db
    volumes:
      - user-data:/var/lib/postgresql/data

  finance-service:
    build:
      context: ./services/finance-service
      dockerfile: Dockerfile
    ports:
      - "3003:3003"
    volumes:
      - finance-data:/var/lib/postgresql/data
    depends_on:
      - finance-db

  finance-db:
    image: postgres:14
    environment:
      POSTGRES_USER: finance_user
      POSTGRES_PASSWORD: finance_pass
      POSTGRES_DB: finance_db
    volumes:
      - finance-data:/var/lib/postgresql/data

  api-gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - auth-service
      - user-service
      - finance-service

volumes:
  auth-data:
  user-data:
  finance-data:
