version: '3.8'
services:
  auth-service:
    build: ./services/auth-service
    ports:
      - "3001:3001"
    environment:
      - AUTH_PORT=3001
      - AUTH_DB_URL=postgresql://auth_user:password@auth-db:5432/auth_db
      - JWT_SECRET=your_jwt_secret
    depends_on:
      - auth-db

  auth-db:
    image: postgres:14
    environment:
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: auth_db
    ports:
      - "5432:5432"
    volumes:
      - auth-data:/var/lib/postgresql/data

volumes:
  auth-data:
